name: ad4m-model

on:
  push:
    paths:
      - apps/tree-of-life/ad4m/**
      - .github/workflows/ad4m-model.yaml

defaults:
  run:
    working-directory: apps/tree-of-life/ad4m

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}--${{ github.workflow }}--node-modules--${{ hashFiles('ui/package-lock.json') }}
          restore-keys: ${{ runner.os }}--${{ github.workflow }}--node-modules--

      - name: Set up nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            substituters = https://cache.nixos.org/ https://perspect3vism.cachix.org https://cache.holo.host/ https://holochain.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.holo.host-1:lNXIXtJgS9Iuw4Cu6X0HINLu9sTfcjEntnrgwMQIMcE= cache.holo.host-2:ZJCkX3AUYZ8soxTLfTb60g+F3MkWD7hkH9y8CgqwhDQ= perspect3vism.cachix.org-1:0LT3Sf7UY2OC3sUV8N5j/ne8+wRC+JItGyfv475lWco= holochain.cachix.org-1:fWOoSTrRQ8XipZim7a8LDqFAE8aqcGnG4E7G8NAJlgY=

      - name: Cache nix with Cachix
        uses: cachix/cachix-action@v10
        with:
          name: holochain
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: cat ~/.config/nix/nix.conf

      # - run: npm install -g @perspect3vism/ad4m-cli@0.0.2
      - run: |
          set -x
          git clone https://github.com/perspect3vism/ad4m-cli.git
          cd ad4m-cli
          git fetch origin pull/2/head:fix-symlink   # https://github.com/perspect3vism/ad4m-cli/pull/2
          git checkout fix-symlink
          npm install
          npm run run serve &

      - run: npm ci # nmp install for CI env
      - run: npm run test:ci
      # - run: npm run lint

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,ref,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI }}
        if: failure()
