name: backend-holochain

on:
  push:
    paths:
      - backend-holochain/**
      - .github/workflows/backend-holochain.yaml

defaults:
  run:
    working-directory: backend-holochain

jobs:
  test-nix:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90

    strategy:
      matrix:
        os: [macos-10.15, macos-11, ubuntu-20.04]
      fail-fast: false

    steps:
      - name: Fetch source code
        uses: actions/checkout@v2

      - name: Setup Xcode version
        if: ${{ runner.os == 'macOS' }}
        uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: latest-stable

      - name: Check macOS version
        if: ${{ runner.os == 'macOS' }}
        run: sw_vers

      - name: Set up nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cache nix with Cachix
        uses: cachix/cachix-action@v10
        with:
          name: holochain
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install recent bash, and set as NIX_BUILD_SHELL # needed by macos, which has an older bash incompatible with nix
        if: ${{ runner.os == 'macOS' }}
        run: echo "NIX_BUILD_SHELL=$(nix-build -A bashInteractive '<nixpkgs>')/bin/bash" >> $GITHUB_ENV

      - name: Prepare Nix environment
        run: nix-shell --command "echo Completed"

      - run: make nix-build

      # - run: make nix-clippy

      - run: make nix-test
        timeout-minutes: 5 # sometimes failing tryorama tests hang...


  # debug_time:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       os: [macos-10.15, macos-11, ubuntu-20.04]
  #     fail-fast: false

  #   steps:
  #     - name: Fetch source code
  #       uses: actions/checkout@v2

  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         # toolchain: nightly
  #         # target: wasm32-unknown-unknown
  #     - run: rustup component list --installed
  #     - run: rustup show

  #     # debugging failing test
  #     - run: date
  #     - run: cd ../.github && rustc debug.rs && ./debug
